### ISSUE TITLE
缺csv文件

### ISSUE THREAD

**Issue by kuaileyuandi** [YuetongXU/CropGBM#1]
你好，我在运行run_test.py文件时，在基因型数据预处理阶段，未发现需要的csv文件，请问作者可以提供这个文件吗？

**Comment by YuetongXU** [comment]
您好，非常感谢您的提醒，这里是我们书写错误，为您造成的困扰我们深感抱歉！

run_test.py 文件是用于 conda 途经下的程序功能检验，不支持其他方式，这里已进行修订。测试文件是不缺少的，请您在 conda 的 cropgbm 下尝试运行 run_test.py 文件。可能路径为 yourpath/miniconda3/pkgs/cropgbm-1.1.2-py39_0/info/test，其中 yourpath 是您安装 conda 的路径。
